name: Validate Flow Quality Scan

on: [pull_request]

jobs:
  flow-scanner-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all branches and commits

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Install flow scanner plugin
        run: echo 'y' | sf plugins:install @corekraft/flow-linter@1.3.0

      - name: Get changed flow files
        id: changed-flows
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.event.pull_request.base.ref }} | grep 'force-app/main/default/flows/.*\.flow-meta\.xml' || echo "")

          # Convert newline-separated files to space-separated to avoid format issues
          CHANGED_FILES="${CHANGED_FILES//$'\n'/ }"

          echo "Changed Flows: $CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Flow Scanner on Changed Flows
        if: env.FILES != ''
        run: |
          sf flow:scan --files $FILES --failon error
