name: Validate LWC Unit Tests
on: [pull_request]

jobs:
  lwc-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npx jest --passWithNoTests
